apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamlit-pvc
  # namespace: {{ .Values.namespace }}
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: streamlit-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
